# Generated by Django 4.1.7 on 2023-03-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='practice/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
