# Generated by Django 4.1.7 on 2023-04-10 04:45

from django.db import migrations, models
import practice.validators


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='static/practice/', validators=[practice.validators.file_size])),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='static/practice/'),
        ),
    ]
